version: "3"

tasks:
  fmt:
    desc: "Format the code"
    dir: packages/tools
    cmds:
      - deno task fmt

  test:
    desc: "Run all tests"
    dir: packages/tools
    cmds:
      - deno task test -- {{.CLI_ARGS}}
  test:pretty:
    desc: "Run all tests with pretty output"
    dir: packages/tools
    cmds:
      - deno test --allow-read --allow-write --allow-env --allow-run {{.CLI_ARGS}}
  test:md:
    desc: "Run markdown-surgeon CLI tests"
    dir: packages/tools
    cmds:
      - deno test --allow-read --allow-write --reporter=dot markdown-surgeon/cli.test.ts {{.CLI_ARGS}}
  test:wl:
    desc: "Run worklog CLI tests"
    dir: packages/tools
    cmds:
      - WORKLOG_TASK_ID= deno test --allow-read --allow-write --allow-env --allow-run --reporter=dot worklog/cli.test.ts {{.CLI_ARGS}}

  check:
    desc: "Check the code (format & type & lint)"
    cmds:
      - deno fmt --check .
      - cd packages/tools && deno task fmt:check
      - cd packages/tools && deno task check
      - cd packages/tools && deno task lint

  validate:
    desc: "Run all checks (code + plugin manifests)"
    cmds:
      - task: validate:code
      - task: validate:plugin

  validate:code:
    desc: "Run code checks (fmt, lint, check, test)"
    cmds:
      - deno fmt --check .
      - cd packages/tools && deno task validate

  validate:plugin:
    desc: "Validate plugin manifests (requires claude CLI)"
    cmds:
      - claude plugin validate .
      - claude plugin validate ./plugins/tools

  validate:ci:
    desc: "Run CI checks (code only)"
    cmds:
      - task: validate:code

  publish:
    desc: "Publish package to JSR"
    dir: packages/tools
    cmds:
      - deno publish

  build:
    desc: "Build binaries for all platforms (usage: task build VERSION=0.4.3)"
    cmds:
      - bash scripts/build.sh {{.VERSION}}
    requires:
      vars: [VERSION]

  bump:
    desc: "Bump version (DEPRECATED - use bump-prepare instead)"
    cmds:
      - echo "⚠️  This task is deprecated. Use 'task bump-prepare' instead."
      - echo "See RELEASE.md for the new two-phase release process."
      - bash scripts/bump-version.sh {{.TOOL}} {{.VERSION}}
    requires:
      vars: [TOOL, VERSION]

  bump-prepare:
    desc: "Prepare version bump (usage: task bump-prepare TOOL=wl TOOL_VERSION=0.6.1 JSR_VERSION=0.6.2)"
    cmds:
      - bash scripts/bump-prepare.sh {{.TOOL}} {{.TOOL_VERSION}} {{.JSR_VERSION}}
    requires:
      vars: [TOOL, TOOL_VERSION, JSR_VERSION]

  bump-finalize:
    desc: "Finalize version bump after GitHub release (usage: task bump-finalize TOOL=wl VERSION=0.6.1)"
    cmds:
      - bash scripts/bump-finalize.sh {{.TOOL}} {{.VERSION}}
    requires:
      vars: [TOOL, VERSION]

  update-tap:
    desc: "Update homebrew tap (usage: task update-tap TOOL=wl VERSION=0.4.3)"
    cmds:
      - bash scripts/update-homebrew-tap.sh {{.TOOL}} {{.VERSION}}
    requires:
      vars: [TOOL, VERSION]

  release:
    desc: "Full release process (usage: task release TOOL=wl VERSION=0.4.3)"
    requires:
      vars: [TOOL, VERSION]
    cmds:
      - echo "🚀 Starting release process for {{.TOOL}} v{{.VERSION}}"
      - task: bump
        vars:
          TOOL: "{{.TOOL}}"
          VERSION: "{{.VERSION}}"
      - echo "📝 Review changes with git diff"
      - echo "✅ If changes look good, run:"
      - |
          echo "   git add -A && git commit -m 'chore({{.TOOL}}): bump to v{{.VERSION}}'"
      - echo "   cd packages/tools && deno publish && cd ../.."
      - echo "   task build VERSION={{.VERSION}}"
      - echo "   ./dist/{{.TOOL}}-darwin-arm64 --version"
      - echo "   git push origin main && git tag {{.TOOL}}-v{{.VERSION}} && git push origin {{.TOOL}}-v{{.VERSION}}"
      - echo "   task update-tap TOOL={{.TOOL}} VERSION={{.VERSION}}"
